version: '3.3'
services:
    docker-ripper:
        container_name: Ripper
        volumes:
            - ./ripper-config:/config:rw
            - ./ripper-output:/out:rw
        devices:
            - /dev/sr0:/dev/sr0
            - /dev/sg0:/dev/sg0
        ports:
            - 9090:9090 
        environment:
            - SEPARATERAWFINISH=true # optional - enable/disable the creation of a separate raw folder - Finished Rips are moved to a "finished" folder in it's respective STORAGE folder
            - EJECTENABLED=false # required - enable/disable ejecting of the disc after ripping
            - STORAGE_CD=/out/Ripper/CD # required - path to the storage folder for CD rips - should be to a folder in the mounted /out volume
            - STORAGE_DVD=/out/Ripper/DVD # required - path to the storage folder for DVD rips - should be to a folder in the mounted /out volume
            - STORAGE_BD=/out/Ripper/BluRay # required - path to the storage folder for BD rips - should be to a folder in the mounted /out volume
            - STORAGE_DATA=/out/Ripper/Data # required - path to the storage folder for Data rips - should be to a folder in the mounted /out volume
            - DRIVE=/dev/sr0 # required - path to the optical drive
            - JUSTMAKEISO=false # optional - enable/disable just making an ISO of any disk
        #    - PREFIX=OPTIONAL_WEB_UI_PATH_PREFIX # optional - path prefix for the integrated web ui
        #    - USER=OPTIONAL_WEB_UI_USERNAME # optional - user name for the integrated web ui (requires PASS to be set)
        #    - PASS=OPTIONAL_WEB_UI_PASSWORD # optional - password for the integrated web ui (requires USER to be set)
        privileged: true
        build:
            dockerfile: latest/Dockerfile
